unique_name: Product
object_type: dimension
label: Product
hierarchies:
  - unique_name: Product Hierarchy
    label: Product Hierarchy
    folder: Product
    levels:
      - unique_name: Product Line
      - unique_name: Product Line
      - unique_name: Product Key
level_attributes:
  - unique_name: Product Line
    label: Product  Line
    contains_unique_names: false
    dataset: DIMPRODUCT
    is_unique_key: false
    key_columns:
      - productline
    name_column: productline
  - unique_name: Product Category
    label: Product Category
    contains_unique_names: false
    dataset: DIMPRODUCT
    is_unique_key: false
    key_columns:
      - productsubcategorykey
      - productline
    name_column: productsubcategoryname
  - unique_name: Product Key
    label: Product Key
    contains_unique_names: false
    dataset: DIMPRODUCT
    is_unique_key: false
    key_columns:
      - productkey
    name_column: productkey
type: standard
