unique_name: Product
object_type: dimension
label: Product
hierarchies:
  - unique_name: Product Hierarchy
    label: Product Hierarchy
    folder: Product
    levels:
      - unique_name: Product Category
      - unique_name: Product Item
level_attributes:
  - unique_name: Product Category
    label: Product Category
    contains_unique_names: false
    dataset: DIMPRODUCT
    is_unique_key: false
    key_columns:
      - productsubcategorykey
    name_column: productsubcategoryname
  - unique_name: Product Item
    label: Product Item
    contains_unique_names: false
    dataset: DIMPRODUCT
    is_unique_key: false
    key_columns:
      - productkey
    name_column: englishproductname
type: standard
